# The Roles of an Innovation Project

## Discovering **[$\text{Au}_{196}^{79}$]**dit Innovation

- locate areas of improvement: can our processes be faster? smarter? better?

- find inspiration from others: ask "what they would do differently" or "what they want to work on"

- discuss with auditors: they're our "customers", we should gather their feedback where possible

## Skepticism, Skepticism, Skepticism

- continuously define/narrow scope; what could/should be done, what couldn't/shouldn't be done

- question if your idea is worth the investment; what reason(s) should you *not* work on this project?

- question if you are capable of implementing this idea; do you have the resources to "solve" the problem(s)?

## Painting a Masterpiece

- draw outlines before coloring; **do not prematurely optimize**, confirm plan before taking action

- consider the end user; multiple rounds of testing, frequent check-ins, always solve for "what do they need?"

- stick to your workbench; **do not** implement fancy solutions, be a lazy programmer, make the most of the budget given to you
