# Contributing to Innovation

Innovation projects are great opportunities for flexing your technical muscles.
Not only do you get to learn about existing business functions (and meet some people
you might otherwise couldn't), but you contribute to developing really
interesting solutions that shape the future of our group.

Fortunately, the barrier for innovation seems to slowly lower as time goes on.
Let's look into how you can overcome this barrier and start contributing to innovation projects.


## Join an Existing Project

The best way to build your "innovation resume" is to join an existing project. There are a lot of cool projects going on at any given time, all of which try to solve their own unique problem(s) by developing their own unique solution(s).

How could you join these projects?

- Keep up to date with innovation resources. Read Things to Know (TTK), stay in touch with people who are in touch with innovation projects, and take the lead on conversations regarding the state of innovation.

- Make your interests common knowledge. If someone tells me they like "x, y, z", well the next time "x, y, z" comes up in conversation, I'll think of them and recommend them if appropriate. Networking always wins.

- Get lucky. Sometimes an innovation project falls in your lap. Better make the most of the opportunity!


## Start Your Own Project

> **Disclaimer**: *Do not rely on this approach. Discuss your ideas with others first. If you decide to prototype your idea before discussing with others, limit the amount of work you do to the bare minimum.*

Rather than waiting for a project to spawn that matches your interests or has a problem statement you can relate to, another valid option for building your "innovation resume" is by creating your own project. Sometimes creating a project is as simple as discussing your idea with a couple others and securing support from them to work on your project. Other times, it's a long, tedious process that requires you to vouch for yourself and your project.

Additionally, innovation projects are internally funded, and with finite resources, we can't support all innovation projects even if their ideas are worth exploring at that point in time.

Regardless of these caveats (which you should not ignore), creating your own project is a rewarding endeavor. The initial stages of a project are the most challenging, and generating your own experiences by managing, developing, and presenting your own product is an invaluable skill that will benefit you anywhere you go. Although I don't consider myself an expert, I've started a couple innovation projects, all of which turned out to be highly beneficial regardless of their current state.

If you do go this route, consider reading [The Roles of an Innovation Project](#02-roles) again as you will be assuming all responsibilities - at least initially - for your project.
